name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    steps:
      - uses: actions/checkout@v2      
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v9